project:
  type: website
  render:
    - index.qmd
    - pages/*qmd

website:
  title: "Katy and Duncan 2026"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - pages/general.qmd
      - pages/timeline.qmd
      - pages/accommodation.qmd
      - pages/parking.qmd
      - pages/food.qmd
      - pages/rsvp.qmd

format:
  html:
    theme:
      - journal
      - custom.scss
    css: custom.scss
    toc: true

filters:
  - quarto
  - fwrappe
